version: "3.7"
services:
  postgres:
    build: ./docker
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - APP_USER=foobar
      - APP_PASSWORD=s3cret
      - APP_DB=foobar
    ports:
      - "6002:5432"
    volumes:
      - .data/postgres:/data/postgres
      - .data/pgdata:/var/lib/postgresql/data

volumes:
  postgres-data: